
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css"; 

import { Toaster } from "@/components/ui/sonner"


import  NavBar  from "../components/nav"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import localFont from 'next/font/local'

const satoshi = localFont({
  src: '../../public/fonts/Satoshi-Variable.ttf',
  weight: '100 900', 
  display: 'swap',
  variable: '--font-satoshi',
})
export const metadata = {
  title: "Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen" style={{ overflow: 'visible' }}>
          <NavBar/>
          <main className="flex-1 p-[1.5rem] pl-[7vw] flex flex-col ">
            {children}
            <Toaster />
          </main>
        </div>
      </body>
    </html>
  );
}
